name = input("Enter your name:")
surname = input("Enter your surname:")
age = input("Enter your age:")
address = input("Enter your address:")
roll = input("Enter your roll:")
religion = input("Enter your religion:")
grade = input("Enter your grade:")
email = input("Enter your email:")
birthday = input("Enter your birthday:")
phone = input("Enter your phone:")
hobby = input("Enter your hobby:")

print("name ", name)
print("surname", surname)
print("address", address)
print("roll", roll)
print("religion", religion)
print("grade", grade)
print("email", email)
print("birthday", birthday)
print("phone", phone)
print("hobby", hobby)